import Header from "@/components/header";
import "@/styles/globals.scss";

import { type Metadata } from "next";
import { Geist, Open_Sans } from "next/font/google";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={[geist.className, openSans.variable].join(" ")}>
        <Suspense>
          <Header />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
